export const conversation = [
    { text: "Hello, how can I assist you today?", name: "Doctor" },
    { text: "Hi, I've been feeling unwell lately.", name: "Patient" },
    { text: "I see. Can you please describe your symptoms?", name: "Doctor" },
    { text: "I have a persistent cough and high fever.", name: "Patient" },
    { text: "Have you experienced any shortness of breath or chest pain?", name: "Doctor" },
    { text: "Yes, I've had difficulty breathing, especially at night.", name: "Patient" },
    { text: "I'm sorry to hear that. It's important to get a proper diagnosis. I recommend you visit a healthcare facility for a thorough examination and testing.", name: "Doctor" },
    { text: "I'm worried it might be COVID-19. What should I do in the meantime?", name: "Patient" },
    { text: "It's essential to self-isolate to prevent potential spread. Rest, drink fluids, and monitor your symptoms. If they worsen, seek medical attention immediately.", name: "Doctor" },
    { text: "Thank you, doctor. I'll follow your advice.", name: "Patient" },
    { text: "You're welcome. Take care, and I hope you feel better soon. Don't hesitate to reach out if you have more questions.", name: "Doctor" },
    { text: "Doctor, I've been taking rest and drinking fluids, but my fever isn't improving.", name: "Patient" },
    { text: "I'm concerned about that. Are you experiencing any other symptoms, such as fatigue or loss of taste or smell?", name: "Doctor" },
    { text: "Yes, I've been feeling extremely tired, and I've lost my sense of taste and smell.", name: "Patient" },
    { text: "These are concerning symptoms. I recommend you contact a healthcare provider immediately for further evaluation and possible COVID-19 testing.", name: "Doctor" },
    { text: "I'll do that right away. What precautions should I take until then?", name: "Patient" },
    { text: "Continue to self-isolate, wear a mask, and practice good hand hygiene. Avoid close contact with others to reduce the risk of transmission.", name: "Doctor" },
    { text: "Thank you for your guidance, doctor.", name: "Patient" },
    { text: "You're welcome. Please don't delay seeking medical attention. Your health is our priority. Keep us updated on your progress.", name: "Doctor" },   
    { text: "Patient: Doctor, I've seen a healthcare provider, and I tested positive for COVID-19.", name: "Patient" },
    { text: "Doctor: I'm sorry to hear that. How are you feeling now? Any changes in your symptoms?", name: "Doctor" },
    { text: "Patient: My fever is still high, and I'm experiencing more fatigue. My sense of taste and smell are gone completely.", name: "Patient" },
    { text: "Doctor: It's crucial to continue monitoring your symptoms and follow the guidance of your healthcare provider. Get plenty of rest and stay hydrated.", name: "Doctor" },
    { text: "Patient: Thank you, doctor. I appreciate your support during this challenging time.", name: "Patient" },
    { text: "Doctor: You're welcome, and remember, you're not alone. Reach out if you have any questions or concerns. We're here to help.", name: "Doctor" },
  ];

  export const symptoms = [
    { text: 'Fever', bgColor: '#DDEBF3' },
    { text: 'Cough', bgColor: '#DDEBF3' },
    { text: 'Headache', bgColor: '#DDEBF3' },
    { text: 'Fatigue', bgColor: '#DDEBF3' },
    { text: 'Seizures', bgColor: '#DDEBF3' },
    { text: 'Bluish lips or face', bgColor: '#DDEBF3' },
    { text: 'Confusion', bgColor: '#EECAC6' },
    { text: 'Hair loss',  bgColor: '#FBE5FE' },
    { text: 'Unexplained weight loss', bgColor: '#FBE5FE' },
    { text: 'Joint pain', bgColor: '#FBE5FE' },
    { text: 'Vision problems',  bgColor: '#FBE5FE' },
    { text: 'Shortness of breath', bgColor: '#FBE5FE' },
    { text: 'New loss of taste or smell', bgColor: '#FBE5FE' },
  ]